### ISSUE TITLE
Using `output` + `suggestions` simultaneously in `fromFixture`

### ISSUE THREAD

**Issue by rafaelss95** [cartant/eslint-etc#5] opened 2021-10-13 00:44 UTC
Consider this scenario:

```ts
fromFixture(
  stripIndents`
import type { OnRunEffects } from '@ngrx/effects'

class NotOk6 {
  @Effect(config)
  ~~~~~~~~~~~~~~~ [${noEffectDecorator}]
  effect = this.actions.pipe(
    ofType('PING'),
    mapTo(CustomActions.pong()),
  )

  @Effect({ dispatch: false })
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [${noEffectDecorator} suggest 0]
  effect2 = createEffect(() => this.actions.pipe(
    ofType('PING'),
    mapTo(CustomActions.pong()),
  ), config)
}`,
      {
        output: stripIndents`bigOutput`,
        suggestions: [
          {
            messageId: noEffectDecoratorSuggest,
            output: `anotherBigOutput`,
          },
        ],
      },
    ),
```

In this specific rule, we can have both `suggestions` and `output`, however `fromFixture` doesn't seem to handle this properly. Currently, I'm receiving this:

> assert.strictEqual(Array.isArray(message.suggestions), true, `Error should have an array of suggestions. Instead received "${message.suggestions}" on error with message: "${message.message}"`);
                                       ^
AssertionError [ERR_ASSERTION]: Error should have an array of suggestions. Instead received "undefined" on error with message: "The `@Effect` decorator is deprecated. Use `createEffect` instead."

It says that `suggestions` is `undefined`, however it shouldn't be.

It's worth noting that it works if I separate in two specs: one for `output` and another for `suggestions`... so the question is: is it a bug or maybe I'm missing something here?

Ah, I also tried to change the `suggest 0` to `suggest` or `suggest 1`, but nothing changed.

**Comment by cartant** [comment] 2021-10-13 04:46
The failure annotations in the fixtures are processed line-by-line. So that you don't have to specify `suggest 0` in fixtures that have a single suggestion, it defaults to using an index of zero. If you have some annotations that don't have suggestions and others that do, you have to specify `suggest` in each annotation - as they are processed line-by-line. See this test:

https://github.com/cartant/eslint-etc/blob/bfd8d844cea2f02d4a9fd17b9727a6f46e24ef50/source/from-fixture-spec.ts#L249-L253

Note the `[whoops suggest]` for the annotation that lacks a suggestion.

**Comment by rafaelss95** [comment] 2021-10-13 11:20
Yes, I see that.. it was like a stab in the dark to make sure the problem really wasn't in the index. I already tried `suggest` too, but the problem is that it doesn't recognizes the `fix` when mixing it with `suggestion`.

**Comment by cartant** [comment] 2021-10-14 02:28
> ... https://github.com/cartant/eslint-etc/issues/5#issuecomment-941917100

That's what I said in [this comment](https://github.com/cartant/eslint-etc/issues/5#issuecomment-941917100). If `suggest` in used in one annotation, it _must_ be used in _all_ annotations within the fixture - as in the test. If no indices are specified for an annotation - e.g. `[whoop suggest]` - that annotation has no suggestion.

**Comment by cartant** [comment] 2021-10-17 00:35
Closing this because, AFAICT, it's working as intended.

FWIW, I've [changed the way that the `suggest` annotation works](https://github.com/cartant/eslint-etc/blob/main/CHANGELOG.md#500-2021-10-16) in v5 of this package. It's primarily a major version bump because of the TS/ESLint major version bump. I don't have the time (or interest) to determine whether or not there will be breaking changes in TS/ESLint that affect this package, so I'm just gonna say that using v5 of this package with ESLint v7 or TS/ESLint v4 is not going to be supported.

**Closed as completed by cartant** 2021-10-17 00:35 UTC
